configured logger and added logger methods
mate-academy/jv-logger pull request #200
Opened 2022-02-14 14:36 UTC by liliia-ponomarenko

2022-02-17 16:08 UTC, anyutamysko commented on src/main/resources/log4j2.xml
> +<Configuration status="WARN">
i think status can be : info

2022-02-17 17:18 UTC, anyutamysko approved these changes
LGTM!

2022-02-23 08:27 UTC, KostyaNikiforov requested changes

2022-02-23 08:27 UTC, KostyaNikiforov commented on .gitignore
> +logs/*
Let's add an empty line to each file you create

2022-02-23 08:27 UTC, KostyaNikiforov commented on src/main/java/mate/academy/Main.java
> +            logger.error("Can't login user", e);
```suggestion
            logger.error("Can't login user bob", e);
```

2022-02-23 08:27 UTC, KostyaNikiforov commented on src/main/java/mate/academy/service/OrderServiceImpl.java
> +        logger.info("data fetched from DB successful");
```suggestion
        logger.info("data fetched from DB successful for user with id {}", userId);
```

2022-02-23 08:41 UTC, KostyaNikiforov approved these changes

2022-11-09 08:10 UTC, closed without merging