my hw jv logger
mate-academy/jv-logger pull request #356
Opened 2022-09-05 13:36 UTC by fifahater

2022-09-05 13:51 UTC, fliarkovskyi commented on src/main/java/mate/academy/service/AuthenticationServiceImpl.java
>          //TODO: add corresponding log message about method login was called
![image](https://user-images.githubusercontent.com/96151185/188465006-5eb935c9-f2c0-4ab1-8091-9904d8ad4971.png)

2022-09-05 13:52 UTC, fliarkovskyi commented on src/main/java/mate/academy/service/OrderServiceImpl.java
>          // TODO: add log message about method completeOrder was called
![image](https://user-images.githubusercontent.com/96151185/188465218-92b4454a-9f4a-4a2d-b666-7c614d9d0dd8.png)

2022-09-05 15:10 UTC, fliarkovskyi approved these changes

2022-09-06 06:34 UTC, Noct2000 requested changes

2022-09-06 06:34 UTC, Noct2000 commented on .gitignore
> +*.log
check your `log4j2.xml`
```suggestion
logs/*
```

2022-09-06 06:34 UTC, Noct2000 commented on src/main/resources/log4j2.xml
> +</Configuration>
add new line to the end of the file

2022-09-06 07:50 UTC, Noct2000 approved these changes

2024-09-17 20:21 UTC, closed without merging