Logger added
mate-academy/jv-logger pull request #418
Opened 2022-10-30 17:04 UTC by Pavlo-Gook

2022-10-31 16:03 UTC, YuriiHryniv approved these changes
Good!

2022-10-31 16:03 UTC, YuriiHryniv commented on src/main/java/mate/academy/service/AuthenticationServiceImpl.java
>              throw new AuthenticationException("Username or password are incorrect");
Personally, I would make this exception message a constant.

2022-10-31 16:03 UTC, YuriiHryniv commented on src/main/java/mate/academy/Main.java
>              user = authenticationService.login("bob", "1234");
I would make these fields constats too etc.

2022-11-01 10:32 UTC, KostyaNikiforov requested changes

2022-11-01 10:32 UTC, KostyaNikiforov commented on src/main/java/mate/academy/Main.java
> +            logger.error("Can't login", e);
Add info about the user to the message

2022-11-01 10:38 UTC, KostyaNikiforov approved these changes

2024-12-15 14:58 UTC, closed without merging