C001 - All Done! For Review!
mate-academy/jv-logger pull request #48
Opened 2021-05-11 16:45 UTC by Koziarevskyi

2021-05-11 19:16 UTC, Anatolii-Zarytskyi requested changes

2021-05-11 19:16 UTC, Anatolii-Zarytskyi commented on src/main/java/mate/academy/Main.java
> +        logger.info("Method \"main\" was called.");
Do yoy need this logger?

2021-05-11 19:16 UTC, Anatolii-Zarytskyi commented on src/main/java/mate/academy/service/AuthenticationServiceImpl.java
> +        logger.info("Method \"login\" was called. Params: login = {}", login);
here we should use logger.debug

2021-05-11 19:16 UTC, Anatolii-Zarytskyi commented on src/main/java/mate/academy/service/OrderServiceImpl.java
> +        logger.info("Method \"completeOrder\" was called. Params: userId = {}", userId);
same

2021-05-11 19:16 UTC, Anatolii-Zarytskyi commented on src/main/java/mate/academy/service/OrderServiceImpl.java
>          // NOTE: In production ready code this order identifier should be generated by DB
remove all comments

2021-05-11 19:34 UTC, Anatolii-Zarytskyi approved these changes

2021-05-12 06:24 UTC, KseniiaMakarova requested changes

2021-05-12 06:24 UTC, KseniiaMakarova commented on src/main/java/mate/academy/Main.java
> +            logger.error("Authentication failed");
```suggestion
            logger.error("Authentication failed", e);
```

2021-05-12 06:24 UTC, KseniiaMakarova commented on src/main/java/mate/academy/service/OrderServiceImpl.java
> +        logger.debug("Method \"getAllProductsFromShoppingCart\" was called. "
let's use `info` for the purpose of tracking business logic flow
we should write a message that data from DB was fetched successfully, not that some method was called

2021-05-12 06:24 UTC, KseniiaMakarova commented on src/main/java/mate/academy/service/OrderServiceImpl.java
> +                + "Data fetched from DB successful. Params: userId = {}", userId);
```suggestion
        logger.info("Data for user {} was fetched from DB successfully.", userId);
```

2021-05-12 07:44 UTC, KseniiaMakarova approved these changes

2026-05-25 10:11 UTC, closed without merging