configured logger, did TODO tasks
mate-academy/jv-logger pull request #838
Opened 2023-11-21 19:33 UTC by maxymmusiienko

2023-11-21 20:02 UTC, Sanderfuck requested changes

2023-11-21 20:02 UTC, Sanderfuck commented on src/main/java/mate/academy/service/AuthenticationServiceImpl.java
>  }
You can log this method

2023-11-21 20:02 UTC, Sanderfuck commented on src/main/java/mate/academy/service/OrderServiceImpl.java
>          Product iphone = new Product("iPhone X", BigDecimal.valueOf(1199));
You can log what userId comming for this method

2023-11-22 13:07 UTC, okuzan approved these changes

2023-11-22 13:07 UTC, okuzan commented on src/main/java/mate/academy/service/AuthenticationServiceImpl.java
> +
```suggestion
```

2026-05-28 12:23 UTC, closed without merging